# Generated by Django 4.1 on 2024-05-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("income", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expense", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("identifier", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("steam_id", models.CharField(max_length=30, unique=True)),
                ("picture", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=30)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=50)),
            ],
        ),
    ]
