# Generated by Django 4.1 on 2024-05-07 09:50

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FavoriteJewelry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="JewelryType",
            fields=[
                ("jewelry_id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="jewelry_images/")),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("name", models.CharField(max_length=50)),
                ("units_sold", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=64)),
                ("steam_id", models.CharField(max_length=30)),
                ("image", models.ImageField(upload_to="user_images/")),
                ("username", models.CharField(max_length=30)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=50)),
                (
                    "favorite_jewelry_types",
                    models.ManyToManyField(
                        through="testapp.FavoriteJewelry", to="testapp.jewelrytype"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("income", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expense", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("identifier", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testapp.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jewelry",
            fields=[
                (
                    "small_jewelry_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "wear_and_tear",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "jewelry_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testapp.jewelrytype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="favoritejewelry",
            name="jewelry_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="testapp.jewelrytype"
            ),
        ),
        migrations.AddField(
            model_name="favoritejewelry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="testapp.user"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favoritejewelry",
            unique_together={("user", "jewelry_type")},
        ),
    ]
